baseURL = "https://albertbling.com"
# include content marked as draft
buildDrafts = false
# include content with publishdate in the future
buildFuture = false
# include content already expired
buildExpired = false
# enable this to make all relative URLs relative to content root. Note that this does not affect absolute URLs.
relativeURLs = true
disableRSS = true
enableRobotsTXT = true
editor = "nano"
languageCode = "en"
language = "en"
theme = "vncnt-hugo"
title = "Albert Bling's landing page"

[blackfriday]
  extensions = ["hardLineBreak"]

[permalinks]
  fixed = ":title/"
  posts = "posts/:slug/"

[params]
  author = "Albert Bling"
  email = "amakina.pm.me"
  description = "Landing Page"
  bio = "My biography is beyond explanation!"
  avatar = "img/avatar.jpeg"
  favicon = "img/favicon.ico"
  error404 = "There is no such page."

  [params.contact]
    github = "https://github.com/AlbertMMM"
    instagram = "https://instagram.com/Blingjee"
    twitter = "https://twitter.com/Blingjee06"
    blog = "https://blog.AlbertBling.com"
